name: test
on:
  workflow_dispatch:
jobs:
  utility-cluster-preconfig:
    runs-on: ubuntu-latest
    steps:
      - name: Install Azure cli
        run: |
          sudo apt-get install ca-certificates curl apt-transport-https lsb-release gnupg
          curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
          AZ_REPO=$(lsb_release -cs)
          echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
          sudo apt-get update
          sudo apt-get install azure-cli    
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: Azure/get-keyvault-secrets@v1
        with: 
          keyvault: "kv-coetools-np-eastus-01"
          secrets: 'dbpass'
        id: coetools
      - name: create a new file
        run: echo '#{db_password}#' > dbstring.txt
      - name: Replace tokens
        uses: cschleiden/replace-tokens@v1.2
        with:
          files: 'dbstring.txt' 
        env:
          db_password: ${{ steps.coetools.outputs.dbpass}}
      - name: cat the file
        run: cat dbstring.txt
